### ISSUE TITLE
Download/Upload files

### ISSUE THREAD

**Issue by jessedobbelaere** [sumocoders/forkcms_deploy#12]
Don't know if this could be useful in the forkcms_deploy gem, but I often use:

```
# Download/upload Fork CMS files
namespace :files do
  desc "Upload local files to the shared files folder on the server"
  task :push do
    top.upload("src/Frontend/Files/.", "#{shared_path}/files/.", :recursive => true, :mode => '755 -R', :via => :scp)
  end

  desc "Download remote files to the local files folder"
  task :pull do
    top.download("#{shared_path}/files/.", "src/Frontend/Files", :via => :scp, :recursive => true)
  end
end
```

Makes it possible for me to **pull the images & other files from the Files folder to my local setup** by executing `cap files:pull` command. This is useful when I should fix a bug and I want to work on exactly the same website on my local machine as the online version. Then I just have to pull the database (with another capistrano plugin) and pull the files to my local machine. It's also possible to upload all your local files to the remote server, but I don't use that very often.

I thought I'd just share this code

**Comment by tijsverkoyen** [comment]
Looks good, at SumoCoders we have our own extension that adds additional tasks, but ours work with rsync to speed up the download/uploading. I will look into it to merge those into this gem.

**Comment by jessedobbelaere** [comment]
Great! I just noticed that [capistrano-db-tasks](https://github.com/sgruhier/capistrano-db-tasks), an extension that I often use to pull & push the database, also includes assets pull/push with rsync so that's another option. It uses Capistrano 3 though. Is the fork cms gem compatible with Capistrano 3? Haven't tried v3 yet.

**Comment by tijsverkoyen** [comment]
It is not compatible with Capistrano v3.

**Comment by WouterSioen** [comment]
Capistrano v2 and v3 are completely different and thus not compatible with each other. It sadly is impossible to write tasks that work for both versions.

**Comment by jessedobbelaere** [comment]
Ok, I thought so :+1:
