### ISSUE TITLE
No install_locale.php

### ISSUE THREAD

**Issue by jessedobbelaere** [sumocoders/forkcms_deploy#13]
I tried deploying with a locale.xml inside a migration folder and I got the error `Could not open input file: install_locale.php`. Took me a few seconds to realise there is no such thing as an install_locale file in forkcms. But found it on the sumocoders repo though :-) 

Maybe add the `install_locale.php` downloadlink to the readme of the deploy gem, or add the file to the forkcms repository? Maybe it's best to explain "migrations" in the readme and what you can do with it (update.sql, locale and php files), with a downloadlink to install_locale.php  😬

**Comment by WouterSioen** [comment]
https://github.com/forkcms/forkcms/commit/113fd6715280e4d519174cd69b391fd0deaf2f96
