### ISSUE TITLE
working fork5

### ISSUE THREAD

**Issue by WouterSchoofs** [sumocoders/forkcms_deploy#28]
I had this error: 

104173015/library/globals.php"
    servers: ["web04.hostbots.be"]
    [web04.hostbots.be] executing command
 ** [out :: web04.hostbots.be] ln: failed to create symbolic link `/home/.../apps/../releases/20171104173015/library/globals.php': No such file or directory
    command finished in 303ms
*** [deploy:update_code] rolling back
 

I'm working with the last fork5 version.

**Comment by tijsverkoyen** [comment]
This gem is not compatibel with Fork 5.0

**Comment by carakas** [comment]
@WouterSchoofs The one for Fork 5.0 and up is https://github.com/tijsverkoyen/capistrano-forkcms
