### ISSUE TITLE
Fork CMS installer bundle

### ISSUE THREAD

**Issue by jessedobbelaere** [sumocoders/forkcms_deploy#6]
Fork CMS doesn't have an `src/Install/Cache/installed.txt` file anymore since the new InstallerBundle. Maybe update the Capistrano gem with a fix? I can't deploy without creating that folder structure and file.

**Comment by WouterSioen** [comment]
@jessedobbelaere this should be fixed, since the 3.8 file is added. Can you test and close if this is not applicable anymore?

**Comment by jessedobbelaere** [comment]
Working :+1:
